use_frameworks!

platform :ios, '11.0'

target 'InteractiveDismiss_Example' do
  pod 'InteractiveDismiss', :path => '../'

  target 'InteractiveDismiss_Tests' do
    inherit! :search_paths

    
  end
end
